twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
    globals:
        assets_image_post_path: '%assets_image_post_path%'

when@test:
    twig:
        strict_variables: true
